stages:
  createmeaningoflife:
    cmd: uv run meaningoflifesimple.py
    deps:
    - meaningoflifesimple.py
    outs:
    - meaning_of_life.txt
  copyfile:
    cmd: cp meaning_of_life.txt meaning_of_life_copy.txt
    deps:
    - meaning_of_life.txt
    outs:
    - meaning_of_life_copy.txt
  createmeaningoflifesinewave:
    cmd: uv run createsinewave.py
    deps:
    - createsinewave.py
    - meaning_of_life_copy.txt
    outs:
    - meaning_of_life_sine_wave.pdf
